name: Create and publish Docker image

on:
  push:
    branches: ['main']
    tags: ['v*.*.*']
  release:
    types: ['prereleased']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title=Yacht
            org.opencontainers.image.url=https://github.com/SelfhostedPro/yacht-api/pkgs/container/yacht-api
            org.opencontainers.image.description=A web interface for managing docker containers with an emphasis on making selfhosting easy
            org.opencontainers.image.documentation=https://yacht.sh/docs/
            org.opencontainers.image.licenses=MIT
            sh.yacht.icon=https://yacht.sh/img/logo.svg
            sh.yacht.self=true
            sh.yacht.ports.3000=WebUI
            sh.yacht.shell=/bin/sh


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64, linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
